---
title: "Hospital Data Analysis"
author: "Jonathan Katz"
date: "November 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/IntroDS/IntroDS_Pierrepont/Rprog/ProgAssessments/ProgAssessment2/")
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
```

## Histogram of 30-day mortality rated from heart attacks

```{r warning=FALSE}
outcome[, 11] <- as.numeric(outcome[, 11])
hist(outcome[, 11])
```

<!-- ## Determining best hospital for heart attack, heart failure or pneumonia -->

<!-- ```{r} -->
<!-- best <- function(state, condition) { -->
<!--   if(!(state %in% outcome[, 7])){ -->
<!--     return("Invalid state") -->
<!--     } -->
<!--   b <- outcome$State == state -->
<!--   switch(condition, -->
<!--          'Heart Attack'={ -->
<!--            col = 11 -->
<!--          }, -->
<!--          'Heart Failure'={ -->
<!--            col = 17 -->
<!--          }, -->
<!--          'Pneumonia'={ -->
<!--            col = 26 -->
<!--          }, -->
<!--          return("Error in best(" + state + ", " + condition + ") : invalid condition") -->
<!--          ) -->

<!--   stateData <- outcome[b,] -->
<!--   stateData[which.min(as.numeric(stateData[,col])), "Hospital.Name"] -->
<!-- } -->
<!-- best("TX", "Heart Attack") -->
<!-- best("TX", "Heart Failuare") -->
<!-- best("MD", "Heart Attack") -->
<!-- best("MD", "Pneumonia") -->
<!-- ``` -->


```{r}
ranking <- function(state, condition, rank = 'best') {
  if(!(state %in% outcome[, 7])){
    return("Invalid state")
  }
  b <- outcome$State == state
  switch(condition,
         'Heart Attack'={
           col = 11
         },
         'Heart Failure'={
           col = 17
         },
         'Pneumonia'={
           col = 23
         },
         return("Error in best(" + state + ", " + condition + ") : invalid condition")
         )
  stateData <- outcome[b,]
  if(rank == "best"){
   stateData[with(stateData, order(stateData[, col], stateData[, 2], decreasing = T)),2]
  }
  else if(rank == "worst"){
   stateData[with(stateData, order(stateData[, col], stateData[, 2], decreasing = F)),2]
  }
  else if(rank > dim(stateData)[1]){
   return(NA)
  }
  else{
   stateData[with(stateData, order(stateData[, col], stateData[, 2], decreasing = T)),2][as.numeric(rank)]
  }
  
}
ranking("TX", "Heart Attack", rank = "worst")
```

```{r}
best <- function(state, condition){
  ranking(state, condition, rank = 1)
}
best("MD", "Pneumonia")
```

```{r}
rankall <- function(condition, rank = "best"){
  top_rankings = data.frame()
  states = unique(outcome[, 7])
  lapply(states, function(f){
    paste(f, ":", ranking(f, condition, 1))
    })
}

rankall("Heart Attack")
```